### ISSUE TITLE
Short description

### ISSUE THREAD

**Issue by zippydodah** [zentyal/zentyal#2064] opened 2021-06-14 02:48 UTC
Receiving error message after logging in:

DBD::mysql::st execute failed: The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. at /usr/share/perl5/EBox/MyDBEngine.pm line 281

Running 
- Zentyal v7.0.4
![zentyal nginx error](https://user-images.githubusercontent.com/85856472/121832996-63b80900-cc99-11eb-8850-a5db2807fdf3.png)

Running: 
- Network
- DNS
- DHCP
- Firewall
- FTP | Stopped
- IDS/IPS | Running
- Logs | Running
- NTP | Running
- RADIUS | Running
- Domain Controller and File Sharing | Running
- HTTP Proxy | Running
-

**Comment by zippydodah** [comment] 2021-06-14 02:49
Rebboting server restores nginx webadmin functionality.

**Comment by djoven89** [comment] 2021-06-28 15:32
Hi @zippudodah ,

Please note that this is a duplicate of the Issue [2055]. You can follow
the updates in the original Issue. Closing the Issue.

[2055]: https://github.com/zentyal/zentyal/issues/2055

Best regards, Daniel Joven.

**Closed by djoven89** 2021-06-28 15:32 UTC
Labels: Type: Bug
