### ISSUE TITLE
LDAP over TLS (STARTTLS) and LDAP over SSL (LDAPS)

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1855] opened 2018-12-07 10:56 UTC
How we can only enable a secure LDAP?

**Comment by Neustradamus** [comment] 2018-12-10 17:18
Yes but by default: 636 instead of 389 and 3269 instead of 3268.

LDAP 389/tcp
LDAP over SSL 636/tcp
Global catalog LDAP 3268/tcp
Global catalog LDAP over SSL 3269/tcp

And disabled insecured ports.

**Comment by Neustradamus** [comment] 2019-05-23 11:46
@brunolorente?

**Comment by loxK** [comment] 2019-05-28 15:27
I can connect using STARTTLS on "non SSL" port with Apache Directory Studio

**Comment by Neustradamus** [comment] 2019-06-01 00:13
@loxK : What modifications have you done?

**Comment by loxK** [comment] 2019-06-04 23:25
none

**Comment by brunolorente** [comment] 2019-07-01 11:19
Thank you for reporting this. Please note that
• this is not a bug, but configuration related error. Please check the official documentation at doc.zentyal.org regarding the feature and ask for help via forum.zentyal.org. 

Closing the issue.

**Closed by brunolorente** 2019-07-01 11:19 UTC
Labels: Status: Invalid

**Comment by Neustradamus** [comment] 2019-11-02 11:17
How it is possible to have a perfect Zentyal with:
- LDAP over TLS (STARTTLS)
- LDAP over SSL (LDAPS)
And disabled insecured ports.

For have:
- LDAP over SSL 636/tcp
- Global catalog LDAP over SSL 3269/tcp

This ticket is not solved.
