### ISSUE TITLE
Zentyal 7 error dns not starting and 504 gateway time out webmin not working  

### ISSUE THREAD

**Issue by nooruddin5** [zentyal/zentyal#2125] opened 2023-03-24 06:32 UTC
administrator@zentyal:~$ sudo zs dns status
[sudo] password for administrator:
Zentyal: status module dns:                     [ STOPPED ]
administrator@zentyal:~$

![Capture](https://user-images.githubusercontent.com/111347422/227443282-775cc11b-49bb-4914-9386-435a5b368c0e.PNG)

**Comment by djoven89** [comment] 2023-03-24 10:48
Hi @nooruddin5 ,

I'm sorry but I have to close this bug. You did not follow the template and also, you did not provide much information to debug.

It looks like an issue in your Zentyal server, not a bug, so use the [forum] instead.

Before closing it, a few things you must analyze:

1. Make sure your Zentyal server is affected by [this](https://github.com/zentyal/zentyal/issues/2121) bug.
2. Ensure your Zentyal server has access to the repositories as [this](https://forum.zentyal.org/index.php/topic,35100.msg115467.html#msg115467) post in the forum explains.
3. If the issue remains, analyze the following log files: `/var/log/zentyal/zentyal.log` and `/var/log/syslog`.

Best regards, Daniel Joven.

**Closed by djoven89** 2023-03-24 10:48 UTC
Labels: Reason: Invalid

**Comment by nooruddin5** [comment] 2023-03-27 05:42
/var/log/zentyal/zentyal.log


2023/03/27 00:00:04 INFO> Service.pm:965 EBox::Module::Service::restartService - Restarting service for module: webadmin
2023/03/27 00:00:06 INFO> SyncDaemon.pm:340 EBox::Samba::SyncDaemon::run - Samba sync daemon started
2023/03/27 00:00:06 ERROR> Sudo.pm:240 EBox::Sudo::_rootError - root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesbfMpd7.ldif failed.
Error output:
Command output: .
Exit value: 1 at root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesbfMpd7.ldif failed.
Error output:
Command output: .
Exit value: 1 at /usr/share/perl5/EBox/Sudo.pm line 240
EBox::Sudo::_rootError('/usr/bin/sudo -p sudo: /var/lib/zentyal/tmp/XfjGeOvzrC.cmd 2> /var/lib/zentyal/tmp/stderr', 'ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesbf>
EBox::Sudo::_root(1, 'ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesbfMpd7.ldif') called at /usr/share/perl5/EBox/Sudo.pm line 153
EBox::Sudo::root('ldbsearch -H /var/lib/samba/private/sam.ldb -s base \'dn\' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesbfMpd7.ldif') called at /usr/share/perl5/EBox/Ldap.pm line 251
EBox::Ldap::dn('EBox::Ldap=HASH(0x559ee90ae3f8)') called at /usr/share/perl5/EBox/Ldap.pm line 293
EBox::Ldap::domainSID('EBox::Ldap=HASH(0x559ee90ae3f8)') called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 232
EBox::Samba::SyncDaemon::setACLs('EBox::Samba::SyncDaemon=HASH(0x559eec4d1a68)') called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 345
EBox::Samba::SyncDaemon::run('EBox::Samba::SyncDaemon=HASH(0x559eec4d1a68)', 30, 10) called at /usr/share/perl5/EBox/Samba/SyncDaemon.pm line 362
2023/03/27 00:00:06 ERROR> Sudo.pm:240 EBox::Sudo::_rootError - root command set -e
/bin/mv /var/lib/zentyal/tmp/KxA5dp2miD '/lib/systemd/system/zentyal.webadmin-nginx.service'
/bin/chmod 0644 '/lib/systemd/system/zentyal.webadmin-nginx.service'
/bin/chown 0.0 '/lib/systemd/system/zentyal.webadmin-nginx.service' failed.
Error output: /bin/mv: inter-device move failed: '/var/lib/zentyal/tmp/KxA5dp2miD' to '/lib/systemd/system/zentyal.webadmin-nginx.service'; unable to remove target: Read-only file system

Command output: .
Exit value: 1 at root command set -e
/bin/mv /var/lib/zentyal/tmp/KxA5dp2miD '/lib/systemd/system/zentyal.webadmin-nginx.service'
/bin/chmod 0644 '/lib/systemd/system/zentyal.webadmin-nginx.service'
/bin/chown 0.0 '/lib/systemd/system/zentyal.webadmin-nginx.service' failed.
Error output: /bin/mv: inter-device move failed: '/var/lib/zentyal/tmp/KxA5dp2miD' to '/lib/systemd/system/zentyal.webadmin-nginx.service'; unable to remove target: Read-only file system

Command output: .
Exit value: 1 at /usr/share/perl5/EBox/Sudo.pm line 240
EBox::Sudo::_rootError('/usr/bin/sudo -p sudo: /var/lib/zentyal/tmp/jskPzkmuCG.cmd 2> /var/lib/zentyal/tmp/stderr', 'set -e^J/bin/mv /var/lib/zentyal/tmp/KxA5dp2miD \'/lib/systemd/system/zentyal.webadmin-nginx.service\'^J/bin/chmod 0644>
EBox::Sudo::_root(1, '/bin/mv /var/lib/zentyal/tmp/KxA5dp2miD \'/lib/systemd/system/zentyal.webadmin-nginx.service\'', '/bin/chmod 0644 \'/lib/systemd/system/zentyal.webadmin-nginx.service\'', '/bin/chown 0.0 \'/lib/systemd/system/zenty>
EBox::Sudo::root('/bin/mv /var/lib/zentyal/tmp/KxA5dp2miD \'/lib/systemd/system/zentyal.webadmin-nginx.service\'', '/bin/chmod 0644 \'/lib/systemd/system/zentyal.webadmin-nginx.service\'', '/bin/chown 0.0 \'/lib/systemd/system/zentyal.w>
EBox::Module::Base::_writeFileSave('/var/lib/zentyal/tmp/KxA5dp2miD', '/lib/systemd/system/zentyal.webadmin-nginx.service', 'HASH(0x562784e98388)') called at /usr/share/perl5/EBox/Module/Base.pm line 1142
EBox::Module::Base::writeConfFileNoCheck('/lib/systemd/system/zentyal.webadmin-nginx.service', 'core/systemd-nginx.mas', 'ARRAY(0x5627809eb5e0)', 'HASH(0x562784e98388)') called at /usr/share/perl5/EBox/WebAdmin.pm line 201
EBox::WebAdmin::_writeNginxConfFile('EBox::WebAdmin=HASH(0x56277d2fe948)') called at /usr/share/perl5/EBox/WebAdmin.pm line 136
EBox::WebAdmin::_setConf('EBox::WebAdmin=HASH(0x56277d2fe948)', 'restart', 1, 'restartModules', 1) called at /usr/share/perl5/EBox/Module/Base.pm line 995
EBox::Module::Base::_regenConfig('EBox::WebAdmin=HASH(0x56277d2fe948)', 'restart', 1, 'restartModules', 1) called at /usr/share/perl5/EBox/Module/Service.pm line 940
EBox::Module::Service::_regenConfig('EBox::WebAdmin=HASH(0x56277d2fe948)', 'restart', 1, 'restartModules', 1) called at /usr/share/perl5/EBox/Module/Service.pm line 967
eval {...} at /usr/share/perl5/EBox/Module/Service.pm line 966
EBox::Module::Service::restartService('EBox::WebAdmin=HASH(0x56277d2fe948)', 'restartModules', 1) called at /usr/share/perl5/EBox/Util/Init.pm line 121
eval {...} at /usr/share/perl5/EBox/Util/Init.pm line 119
EBox::Util::Init::moduleAction('webadmin', 'restartService', 'restart') called at /usr/share/perl5/EBox/Util/Init.pm line 247
EBox::Util::Init::moduleRestart('webadmin') called at /usr/share/zentyal/restart-trigger line 35
2023/03/27 00:00:06 ERROR> Service.pm:969 EBox::Module::Service::restartService - Error restarting service: root command set -e
/bin/mv /var/lib/zentyal/tmp/KxA5dp2miD '/lib/systemd/system/zentyal.webadmin-nginx.service'
/bin/chmod 0644 '/lib/systemd/system/zentyal.webadmin-nginx.service'
/bin/chown 0.0 '/lib/systemd/system/zentyal.webadmin-nginx.service' failed.
Error output: /bin/mv: inter-device move failed: '/var/lib/zentyal/tmp/KxA5dp2miD' to '/lib/systemd/system/zentyal.webadmin-nginx.service'; unable to remove target: Read-only file system

Command output: .
Exit value: 1
2023/03/27 00:00:06 ERROR> Service.pm:971 EBox::Module::Service::restartService - root command set -e
/bin/mv /var/lib/zentyal/tmp/KxA5dp2miD '/lib/systemd/system/zentyal.webadmin-nginx.service'
/bin/chmod 0644 '/lib/systemd/system/zentyal.webadmin-nginx.service'
/bin/chown 0.0 '/lib/systemd/system/zentyal.webadmin-nginx.service' failed.
Error output: /bin/mv: inter-device move failed: '/var/lib/zentyal/tmp/KxA5dp2miD' to '/lib/systemd/system/zentyal.webadmin-nginx.service'; unable to remove target: Read-only file system


/var/log/syslog.

Mar 27 00:00:01 zentyal kernel: [219131.925666] zentyal-firewall drop IN=eth1 OUT= MAC=ff:ff:ff:ff:ff:ff:e0:d5:5e:20:7d:32:08:00 SRC=192.168.1.18 DST=192.168.1.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=31953 PROTO=UDP SPT=137 DPT=137 LEN>
Mar 27 00:00:01 zentyal systemd[1]: zentyal.loggerd.service: Main process exited, code=exited, status=9/n/a
Mar 27 00:00:01 zentyal systemd[1]: zentyal.loggerd.service: Failed with result 'exit-code'.
Mar 27 00:00:02 zentyal systemd[1]: zentyal.loggerd.service: Scheduled restart job, restart counter is at 1.
Mar 27 00:00:02 zentyal systemd[1]: Stopped Zentyal logger daemon.
Mar 27 00:00:02 zentyal systemd[1]: Started Zentyal logger daemon.
Mar 27 00:00:03 zentyal perl[835866]: root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesjiJ1wR.ldif failed.
Mar 27 00:00:03 zentyal perl[835866]: Error output:
Mar 27 00:00:03 zentyal perl[835866]: Command output: .
Mar 27 00:00:03 zentyal kernel: [219133.434936] zentyal-firewall drop IN=eth1 OUT= MAC=ff:ff:ff:ff:ff:ff:d8:5e:d3:89:65:de:08:00 SRC=192.168.1.27 DST=192.168.1.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=24245 PROTO=UDP SPT=137 DPT=137 LEN>
Mar 27 00:00:03 zentyal perl[835866]: Exit value: 1
Mar 27 00:00:03 zentyal systemd[1]: zentyal.samba-sync.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 00:00:03 zentyal systemd[1]: zentyal.samba-sync.service: Failed with result 'exit-code'.
Mar 27 00:00:03 zentyal systemd[1]: zentyal.samba-sync.service: Scheduled restart job, restart counter is at 73646.
Mar 27 00:00:03 zentyal systemd[1]: Stopped Zentyal daemon to check uid and gid numbers.
Mar 27 00:00:03 zentyal systemd[1]: Started Zentyal daemon to check uid and gid numbers.
Mar 27 00:00:04 zentyal kernel: [219134.437361] zentyal-firewall drop IN=eth0 OUT= MAC=ff:ff:ff:ff:ff:ff:50:3e:aa:13:b5:27:08:00 SRC=10.25.68.197 DST=10.25.68.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=28450 PROTO=UDP SPT=137 DPT=137 LEN=>
Mar 27 00:00:05 zentyal kernel: [219135.202886] zentyal-firewall drop IN=eth0 OUT= MAC=ff:ff:ff:ff:ff:ff:50:3e:aa:13:b5:27:08:00 SRC=10.25.68.197 DST=10.25.68.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=28451 PROTO=UDP SPT=137 DPT=137 LEN=>
Mar 27 00:00:06 zentyal perl[835973]: root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesbfMpd7.ldif failed.
Mar 27 00:00:06 zentyal perl[835973]: Error output:
Mar 27 00:00:06 zentyal perl[835973]: Command output: .
Mar 27 00:00:06 zentyal perl[835973]: Exit value: 1
Mar 27 00:00:06 zentyal systemd[1]: zentyal.samba-sync.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 00:00:06 zentyal systemd[1]: zentyal.samba-sync.service: Failed with result 'exit-code'.
Mar 27 00:00:06 zentyal kernel: [219136.667445] zentyal-firewall drop IN=eth1 OUT= MAC=ff:ff:ff:ff:ff:ff:e0:d5:5e:e4:33:b8:08:00 SRC=192.168.1.25 DST=192.168.1.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=27758 PROTO=UDP SPT=137 DPT=137 LEN>
Mar 27 00:00:06 zentyal systemd[1]: zentyal.samba-sync.service: Scheduled restart job, restart counter is at 73647.
Mar 27 00:00:06 zentyal systemd[1]: Stopped Zentyal daemon to check uid and gid numbers.
Mar 27 00:00:06 zentyal systemd[1]: Started Zentyal daemon to check uid and gid numbers.
Mar 27 00:00:06 zentyal logrotate[836034]:  * Restarting Zentyal module: webadmin
Mar 27 00:00:06 zentyal logrotate[836034]:    ...fail!
Mar 27 00:00:07 zentyal systemd[1]: Reloading.
Mar 27 00:00:07 zentyal kernel: [219137.514985] zentyal-firewall drop IN=eth1 OUT= MAC=ff:ff:ff:ff:ff:ff:e0:d5:5e:e4:33:b8:08:00 SRC=192.168.1.25 DST=192.168.1.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=27764 PROTO=UDP SPT=137 DPT=137 LEN>
Mar 27 00:00:07 zentyal systemd[1]: Stopping Zentyal logger daemon...
Mar 27 00:00:07 zentyal systemd[1]: zentyal.loggerd.service: Succeeded.
Mar 27 00:00:07 zentyal systemd[1]: Stopped Zentyal logger daemon.
Mar 27 00:00:07 zentyal systemd[1]: Started Zentyal logger daemon.
Mar 27 00:00:07 zentyal logrotate[836089]:  * Restarting Zentyal module: logs
Mar 27 00:00:07 zentyal logrotate[836089]:    ...done.
Mar 27 00:00:07 zentyal systemd[1]: logrotate.service: Succeeded.
Mar 27 00:00:07 zentyal systemd[1]: Finished Rotate log files.
Mar 27 00:00:09 zentyal kernel: [219139.429026] zentyal-firewall drop IN=eth1 OUT= MAC=ff:ff:ff:ff:ff:ff:d8:5e:d3:89:65:de:08:00 SRC=192.168.1.27 DST=192.168.1.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=24248 PROTO=UDP SPT=137 DPT=137 LEN>
Mar 27 00:00:09 zentyal perl[836023]: root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesoF6Tgz.ldif failed.
Mar 27 00:00:09 zentyal perl[836023]: Error output:
Mar 27 00:00:09 zentyal perl[836023]: Command output: .
Mar 27 00:00:09 zentyal perl[836023]: Exit value: 1
Mar 27 00:00:09 zentyal systemd[1]: zentyal.samba-sync.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 00:00:09 zentyal systemd[1]: zentyal.samba-sync.service: Failed with result 'exit-code'.
Mar 27 00:00:09 zentyal systemd[1]: zentyal.samba-sync.service: Scheduled restart job, restart counter is at 73648.
Mar 27 00:00:09 zentyal systemd[1]: Stopped Zentyal daemon to check uid and gid numbers.
Mar 27 00:00:09 zentyal systemd[1]: Started Zentyal daemon to check uid and gid numbers.
Mar 27 00:00:10 zentyal kernel: [219140.515598] zentyal-firewall drop IN=eth1 OUT= MAC=ff:ff:ff:ff:ff:ff:e0:d5:5e:e4:33:b8:08:00 SRC=192.168.1.25 DST=192.168.1.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=27784 PROTO=UDP SPT=137 DPT=137 LEN>
Mar 27 00:00:11 zentyal kernel: [219141.515615] zentyal-firewall drop IN=eth1 OUT= MAC=ff:ff:ff:ff:ff:ff:e0:d5:5e:e4:33:b8:08:00 SRC=192.168.1.25 DST=192.168.1.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=27790 PROTO=UDP SPT=137 DPT=137 LEN>
Mar 27 00:00:12 zentyal perl[836114]: root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesC7IwKb.ldif failed.
Mar 27 00:00:12 zentyal perl[836114]: Error output:
Mar 27 00:00:12 zentyal perl[836114]: Command output: .
Mar 27 00:00:12 zentyal perl[836114]: Exit value: 1
Mar 27 00:00:12 zentyal systemd[1]: zentyal.samba-sync.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 00:00:12 zentyal kernel: [219142.515641] zentyal-firewall drop IN=eth1 OUT= MAC=ff:ff:ff:ff:ff:ff:e0:d5:5e:e4:33:b8:08:00 SRC=192.168.1.25 DST=192.168.1.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=27796 PROTO=UDP SPT=137 DPT=137 LEN>
Mar 27 00:00:12 zentyal systemd[1]: zentyal.samba-sync.service: Failed with result 'exit-code'.
