### ISSUE TITLE
Cannt bind using LDAPS

### ISSUE THREAD

**Issue by ELCarmen01** [zentyal/zentyal#2063] opened 2021-06-11 21:10 UTC
Hello,
I am pretty new to zentyal and I am trying to bind to Zentyal Users and Computers using LDAPs port 636, I can bind to it using LDAP port 389. but for some reason I Cant get it done with port 636. I created a new service LDAPs port and went to Filtering rules from external networks to Zentyal and enable it there but still did not work.

Please help

**Comment by jose102002** [comment] 2021-06-21 04:49
Hello,

I am trying to get LDAP using port 389 working but not sure how. Can you give me some insight into how you accomplished this? When I try to connect to LDAP from different services, it gives me authentication errors.

**Comment by djoven89** [comment] 2021-06-28 15:44
Hi,

I'm sorry but I have to close the ticket, because this is not a bug or an enhancement, it is just a technical question, and also, you didn't follow any template.

Before closing the issue, a few considerations:

1. Read [this article] from Samba where they explain how implement Samba over SSL.
2. Remember to use the [stub] feature to implement the changes in the configuration file `/etc/samba/smb.conf`.
3. Don't forget to check if there is a rule that allows the traffic for the new port.

[this article]: https://wiki.samba.org/index.php/Configuring_LDAP_over_SSL_(LDAPS)_on_a_Samba_AD_DC
[stub]: https://doc.zentyal.org/en/appendix-c.html#stubs

If you have any doubt, please, use the [forum].

[forum]: https://forum.zentyal.org/index.php?board=10.0

Best regards, Daniel Joven.

**Closed by djoven89** 2021-06-28 15:44 UTC
Labels: Reason: Invalid
