### ISSUE TITLE
Windows 11 22H2 cannot join domain.

### ISSUE THREAD

**Issue by peptoniet** [zentyal/zentyal#2106] opened 2022-10-07 09:58 UTC
**Describe the bug**
Windows 11 22H2 cannot join domain.

**To Reproduce**
1. Try to join Windows 11 Pro version 22H2 to Zentyal
2. Windows shows error stating user and/or password are incorrect.

**Expected behavior**
Workstation joins domain.

**Screenshots**
NA

**Zentyal OS (please complete the following information):**
 - Version: 6.2 and 7.0.2

**Comment by peptoniet** [comment] 2022-10-07 14:44
@brunolorente @djoven89

The problem seems to be in the Heimdal Kerberos module from samba prior to version 8.0
The problem was corrected in Heimdal version 8.0
Samba 4.16.0 apparently uses Heimdal version 8.0
Zentyal 7.0.2 still uses samba version 4.13.17...
A path to upgrade samba to, at least, 4.13.17 would be a possible solution.

https://old.reddit.com/r/sysadmin/comments/xoqend/samba_495_windows_11_22h2_kerberos/iq0c2vo/

**Comment by peptoniet** [comment] 2022-10-07 14:47
As stated here: https://forum.zentyal.org/index.php/topic,35474.0.html and here: https://lists.samba.org/archive/samba/2022-April/240502.html a workaround for joining the domain is to configure local security policies.
But GPO are not being applied.  gpupdate /force returns error if invoked.

Thanks.

**Comment by peptoniet** [comment] 2022-10-07 15:40
Apparently, dynamic DNS is also not working.  Client cannot update DNS register on Zentyal server (permission denied)

**Comment by peptoniet** [comment] 2022-10-07 15:52
After joining the domain, network is not identified as "domain" but as "public".  No options to change to "domain", only to change to "private"

**Comment by peptoniet** [comment] 2022-10-08 17:46
@brunolorente @djoven89 Please, could you tell us, in two words, what is the roadmap...?  Thank you very much in advance.

**Comment by Neustradamus** [comment] 2022-10-16 10:45
To follow this ticket

**Comment by atol71** [comment] 2022-10-24 11:10
djoven89 11 days ago (13. October 2022) states that: 
> We will release a new Zentyal 8.0 based on Ubuntu 22 in May.
May is the 5th month of the year and one can not release something in May if it is already October.

**Comment by peptoniet** [comment] 2022-10-24 11:29
It is difficult to me to join the words "internal policy" and "internal list" and "we cannot talk publicly" with open source.
To me, this is not an open source project.  All the implementations seem to be done in private repositories (please, correct me if I am wrong, and I will apologize).
Pull requests are hurtingly ignored.  This is the worst part: people trying to contribute, but being let down for years... (take a look at the pull requests...)
Again, correct me if I am wrong, but Zentyal was never an open source project.  Source code is being published not as is approved, but as is convenient for the developers.
I would not come back here if some people did not try to convince me about nonsense.

@atol71 Very good point.  Again, 7 months for a new version...

Ok, Zentyal, as you wish.  To anyone who wants to listen, I am migrating to Univention Corporate server.  All lab tests have been succesful, very clean and stable system, fully compatible, well mantained, with a great support forum, and frankly much more functionality than Zentyal.

To me, Zentyal is dead.  A system is dead if users abandon it.

**Comment by seederp2p** [comment] 2022-10-31 10:03
This is something that we should not wait 7 months for.

**Comment by peptoniet** [comment] 2022-10-31 10:07
> This is something that we should not wait 7 months for.

Very true.  I already started migrating all my customers to Univention.

**Comment by seederp2p** [comment] 2022-10-31 11:14
> > This is something that we should not wait 7 months for.
> 
> Very true. I already started migrating all my customers to Univention.

Is it free?

**Comment by peptoniet** [comment] 2022-10-31 11:18
> > > This is something that we should not wait 7 months for.
> > 
> > 
> > Very true. I already started migrating all my customers to Univention.
> 
> Is it free?

Yes. Univention is true open source, not a toy...

**Comment by seederp2p** [comment] 2022-11-02 14:59
I took a look into Univention UCS and I think it won't be the best move to me.

It relies on its own concepts of "domain" even though it has Samba 4 support.

So,  I'll be moving to a Samba 4 installation from scratch if Zentyal keeps this policy.

I've been using Zentyal for 7 years, I had some issues here and there but nothing that wasn't recoverable. However it's clear that this isn't a true "community" project and it has very limited "support". So in the end it will be better to have my own install of samba 4.

You have very good documentation here if you want to build your own server:
https://samba.tranquil.it/doc/en/

**Comment by djoven89** [comment] 2022-11-03 15:57
Hi,

There is still no solution for this issue from Samba, in fact, they seems to be working to apply the fix in Ubuntu 22.04 as [this](https://bugzilla.samba.org/show_bug.cgi?id=15197) link explains.

We were thinking in a workaround until Zentyal 8.0 is released so people can use Windows 11 in their domains, and we found a valid solution that worked in an internal lab. Basically, the solution consists of installing Ubuntu 22.10 and configuring it as an additional domain controller, so Windows 11 computers will only connect to this server for getting a Kerberos ticket, and with that ticket, they will be able to use any shared resources from Zentyal.

We created a complete document where we explain how to achieve this. [Here](https://doc.zentyal.org/en/workaround-windows11.html) is the link in English and [Here](https://doc.zentyal.org/es/workaround-windows11.html) in Spanish. In case of issues or enhancements, please, provide us with all the details possible so we can modify the document.

We really hope this 'workaround' is enough until either way, Samba fixes the issue on Ubuntu 20.04 or Zentyal 8.0 is released.

Best regards, Daniel Joven.

**Comment by brunolorente** [comment] 2022-11-03 16:10
About your comments, we completely understand your frustration, but we cannot release Zentyal 8.0 earlier despite the impact of this unfortunate bug. You must understand that a major release is a complex task, especially this one (Ubuntu 20.04 -> 22.04).
@peptoniet, we are a small team, but the way we interact with the community must be improved and we are working on this task right now, especially regarding the feedback for the Pull requests you mentioned. However, the rest of your points aren't right:
1. The code is public, in fact, you can verify any change we made in the repository log/history if you wish.
2. You can modify the code of any module so it fulfills any possible requirement for a project you might have.
3. Like any product, we defined internal policies based on several factors like maintenance, effort, the time we can spend, and the needs and wishes of our customers.
4. We do not share the roadmap because it often changes because of the discovery of new bugs with a critical impact, sometimes a task is more complex than we expected, etc. So, in the end, it could cause confusion to anyone who checks it regularly.
5. Zentyal is not a 'toy', we have a large community and thousands and thousands of customers who trust and use Zentyal every day in production for their business.
On the other hand, we will analyze a way to share certain parts of this roadmap so you can be aware of the current status, as we really appreciate your feedback.
6. You also have the chance of buying a license to receive more direct feedback and personal support from the tech team.
7. This is an open-source project, and bug fixing is a challenge that the entire community accepts.
Finally, it is sad to hear that you both want to change Zentyal for another product however, do not use this issue to help you to move from Zentyal to another production, that is very disrespectful.  As a reminder, the code is public as we said, so you can provide ideas, workarounds, or other ways to help with the issue.

Please check out the link that @djoven89 shared [here](https://github.com/zentyal/zentyal/issues/2106#issuecomment-1302325083) and give us feedback about this workaround.

Finally, remember that you have to use the issue template in order to help us to understand, track and tag each new issue, so, I'm going to close this issue, please, I appreciate it if you open a new one following the template.

Best regards,

**Closed by brunolorente** 2022-11-03 16:10 UTC
Labels: Type: Bug

**Comment by seederp2p** [comment] 2022-11-03 23:38
> Hi,
> 
> There is still no solution for this issue from Samba, in fact, they seems to be working to apply the fix in Ubuntu 22.04 as [this](https://bugzilla.samba.org/show_bug.cgi?id=15197) link explains.
> 
> We were thinking in a workaround until Zentyal 8.0 is released so people can use Windows 11 in their domains, and we found a valid solution that worked in an internal lab. Basically, the solution consists of installing Ubuntu 22.10 and configuring it as an additional domain controller, so Windows 11 computers will only connect to this server for getting a Kerberos ticket, and with that ticket, they will be able to use any shared resources from Zentyal.
> 
> We created a complete document where we explain how to achieve this. [Here](https://doc.zentyal.org/en/workaround-windows11.html) is the link in English and [Here](https://doc.zentyal.org/es/workaround-windows11.html) in Spanish. In case of issues or enhancements, please, provide us with all the details possible so we can modify the document.
> 
> We really hope this 'workaround' is enough until either way, Samba fixes the issue on Ubuntu 20.04 or Zentyal 8.0 is released.
> 
> Best regards, Daniel Joven.

I just started the process to migrate to my own 22.04 servers and till now, no problems whatsoever with 22h2 :)

Samba version 4.17.2

**Comment by piter76** [comment] 2022-11-07 13:43
Try this: **gpedit.msc**

Local Security Policy> Local Policies> Security Options> Network security: Configure encryption types allowed for Kerberos Check only DES_CBC_CRC and DES_CBC_MD5

Credit: u/cjbarone/ - https://www.reddit.com/r/windowsinsiders/comments/t1f7hu/cannot_connect_to_samba_ad_dc_on_windows_11_dev/

This is worked for me.

**Comment by peptoniet** [comment] 2022-11-07 13:47
> Try this: **gpedit.msc**
> 
> Local Security Policy> Local Policies> Security Options> Network security: Configure encryption types allowed for Kerberos Check only DES_CBC_CRC and DES_CBC_MD5
> 
> Credit: u/cjbarone/ - https://www.reddit.com/r/windowsinsiders/comments/t1f7hu/cannot_connect_to_samba_ad_dc_on_windows_11_dev/
> 
> This is worked for me.

This solution will only allow the computer to join the domain.  Still, the GPO will not be sincronized, and Dinamic DNS records for the workstation will not be updated.
There is no complete solution for these problem, other than user a version of samba which supports the changes made by Microsoft on 22H2 update.
There are reporst of joined workstations with this method that later do not accept user/password authentication.

**Comment by piter76** [comment] 2022-11-07 13:56
And I was glad that I can easily get around it. Pity :(. Well, so on we are still waiting for the right solution.

**Comment by peptoniet** [comment] 2022-11-08 06:01
> The solution is to add the upgrade of Samba, it is easy.

Hello.  In this, I have to agree with the Zentyal developers.  It is not easy to integrate the new version of samba into the old version of Ubuntu.
But this is the real problem: hanging for years on old versions of the operating system...  When something like this happens, you are tied.  (and also, they are far behind LTS versions of Ubuntu...)
On the other hand, solutions like Univention are based on Debian.  But not only this:  Univention mantains it's own package repositories, which means they can install whatever they like.  Of course, this is a lot of work.  But always remember Zentyal only has a small team...

**Comment by djoven89** [comment] 2022-11-10 09:25
Hi,

Just to mention here even knowing that the issue is closed, we have updated the documentation we provided last week and we have added a new workaround. In case of doubt, please, use [this] link. If you have any issues or you want to provide any enhancements, create a new issue using the template.

[this]: https://forum.zentyal.org/index.php/topic,35474.msg115255.html#msg115255

Best regards, Daniel Joven.
