### ISSUE TITLE
After upgrade to Zentyal 6.2 is removed Antivirus and Mail filter

### ISSUE THREAD

**Issue by ivosm** [zentyal/zentyal#1970] opened 2020-05-25 19:27 UTC
During the upgrade done through webadmin is removed the package zentyal-antivirus and zentyal-mailfilter because of it depends on it. 

The reason are unmet dependencies:

Depends: zentyal-core (>= 6.2.0), zentyal-core (<< 7.0.0), zentyal-firewall,
         libclamav9 (= 0.102.2+dfsg-0ubuntu0.18.04.1), clamav (= 0.102.2+dfsg-0ubuntu0.18.04.1), 
         clamav-base (= 0.102.2+dfsg-0ubuntu0.18.04.1), clamav-daemon (= 0.102.2+dfsg-0ubuntu0.18.04.1), 
         clamav-freshclam (= 0.102.2+dfsg-0ubuntu0.18.04.1),libfile-readbackwards-perl, ${misc:Depends}	

Specifically requested version  0.102.2 while only 0.102.3 is available.

**Comment by Daniel-Furcht** [comment] 2020-05-26 22:39
Related to this error, its not possible install antivirus module on fresh install wtih development iso 6.2.

**Comment by petrocc** [comment] 2020-05-27 14:45
The error I get (on initial install) is: 

The following packages have unmet dependencies:
zentyal-antivirus : Depends: libclamav9 (= 0.102.2+dfsg-0ubuntu0.18.04.1) but 0.102.3+dfsg-0ubuntu0.18.04.1 is to be installed
Depends: clamav (= 0.102.2+dfsg-0ubuntu0.18.04.1)
Depends: clamav-base (= 0.102.2+dfsg-0ubuntu0.18.04.1) but 0.102.3+dfsg-0ubuntu0.18.04.1 is to be installed
Depends: clamav-daemon (= 0.102.2+dfsg-0ubuntu0.18.04.1) but 0.102.3+dfsg-0ubuntu0.18.04.1 is to be installed
Depends: clamav-freshclam (= 0.102.2+dfsg-0ubuntu0.18.04.1) but 0.102.3+dfsg-0ubuntu0.18.04.1 is to be installed

The root of the problem is that Ubuntu upgraded ClamAV packages from 0.102.2 to 0.102.3. This cased breakage in the zentyal-antivirus package because  is the control file has:
Depends: zentyal-core (>= 6.2.0), zentyal-core (<< 7.0.0), zentyal-firewall, libclamav9 (= 0.102.2+dfsg-0ubuntu0.18.04.1), clamav (= 0.102.2+dfsg
-0ubuntu0.18.04.1), clamav-base (= 0.102.2+dfsg-0ubuntu0.18.04.1), clamav-daemon (= 0.102.2+dfsg-0ubuntu0.18.04.1), clamav-freshclam (= 0.102.2+d
fsg-0ubuntu0.18.04.1), libfile-readbackwards-perl

It should either be:
Depends: zentyal-core (>= 6.2.0), zentyal-core (<< 7.0.0), zentyal-firewall, libclamav9 (= 0.102.3+dfsg-0ubuntu0.18.04.1), clamav (= 0.102.3+dfsg
-0ubuntu0.18.04.1), clamav-base (= 0.102.3+dfsg-0ubuntu0.18.04.1), clamav-daemon (= 0.102.3+dfsg-0ubuntu0.18.04.1), clamav-freshclam (= 0.102.3+d
fsg-0ubuntu0.18.04.1), libfile-readbackwards-perl

(If you do this you will need to put some process in place to track the upstream dependencies and rebuild the package whenever upstream changes)

Or:
Depends: zentyal-core (>= 6.2.0), zentyal-core (<< 7.0.0), zentyal-firewall, libclamav9 (>= 0.102.2+dfsg-0ubuntu0.18.04.1), clamav (>= 0.102.2+dfsg
-0ubuntu0.18.04.1), clamav-base (>= 0.102.2+dfsg-0ubuntu0.18.04.1), clamav-daemon (>= 0.102.2+dfsg-0ubuntu0.18.04.1), clamav-freshclam (>= 0.102.2+d
fsg-0ubuntu0.18.04.1), libfile-readbackwards-perl

(this way is *fairly* future proof)

I modified the control file in the test vm I'd been trying to deploy to the later ( setting >=) and rebuilt the .deb file and it installed ok:

The following NEW packages will be installed:
  clamav clamav-base clamav-daemon clamav-freshclam libclamav9 libfile-readbackwards-perl libllvm3.9 libmspack0 libtfm1 zentyal-antivirus
0 upgraded, 10 newly installed, 0 to remove and 7 not upgraded.
Need to get 12.8 MB/12.9 MB of archives.
After this operation, 51.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 /home/mailadmin/zentyal-antivirus/test.deb zentyal-antivirus all 6.2.0 [15.1 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 clamav-base all 0.102.3+dfsg-0ubuntu0.18.04.1 [69.4 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 libllvm3.9 amd64 1:3.9.1-19ubuntu1 [11.4 MB]
Get:4 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libclamav9 amd64 0.102.3+dfsg-0ubuntu0.18.04.1 [852 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 clamav-freshclam amd64 0.102.3+dfsg-0ubuntu0.18.04.1 [93.5 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 clamav amd64 0.102.3+dfsg-0ubuntu0.18.04.1 [124 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 clamav-daemon amd64 0.102.3+dfsg-0ubuntu0.18.04.1 [231 kB]
<...>

Setting up zentyal-antivirus (6.2.0) ...
Processing triggers for systemd (237-3ubuntu10.40) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for zentyal-core (6.2.0) ...
 * Restarting Zentyal module: webadmin                                                                                   [ OK ] 
 * Restarting Zentyal module: logs                                                                                             [ OK ]

**Comment by skeelkat** [comment] 2020-05-28 10:22
Successfully installed both zentyal-antivirus and zentyal-mailfilter using the >= dependency trick, however no matter what I do the MailFilter Module will not start.

**Comment by HAL9OO0** [comment] 2020-05-28 10:54
Same Problem here.

There seems to be a workaround [here](https://forum.zentyal.org/index.php/topic,34976.0.html).

Will the bug be fixed soon or should I consider the workaround?

**Comment by brunolorente** [comment] 2020-05-28 13:38
Hi everyone,

We have confirmed that there is a bug with the zentyal-antivirus package caused by a recent update of the ClamAV package. We are working to fix it as soon as possible. A new zentyal-antivirus version will be released tooday or tomorrow.

On the other hand @ivosm , please, when you need to open a new ticket, use the provided template, by this way we are able to automate several things that help us a lot.


Many thanks for your time

**Comment by ivosm** [comment] 2020-05-28 15:31
OK I'll take it to heart. I've just given preference the principle of adequacy, i.e. not to spend more time with reporting the bug than to solving it. Especially when title itself is almost enough. 
Actually it was a report after few years after I spend some time with reporting few bugs not so easy to reproduce incl. testing the reproducibility on newly installed system but then just the whole bug reporting system disappeared and new one and clean on Github started. No word about the reports in the old one. And you know, nobody of us likes to do unnecessary work. 
I appreciate your care about Zentyal and I'll try to save your work next time. :-)

**Comment by Justinzobel** [comment] 2020-05-31 12:13
Hi @brunolorente any update on the new `zentyal-antivirus` release?

**Comment by Justinzobel** [comment] 2020-06-02 04:53
Can we please have an update on this. The fix appears fairly simple.

**Closed** 2020-06-03 05:40 UTC
Labels: Status: Roadmap, Type: Bug

**Comment by Justinzobel** [comment] 2020-06-03 07:25
Still getting an error after apt-get update and hitting Update List in Zentyal components area:
![image](https://user-images.githubusercontent.com/1370117/83607791-fe780500-a5ba-11ea-98ef-20e8417ad55b.png)

**Comment by krejcar25** [comment] 2020-06-03 09:26
That is not even Zentyal's cache or anything, it happens even when `apt install zentyal-antivirus zentyal-mailfilter` is ran from command line, after `apt upgrade`

**Comment by brunolorente** [comment] 2020-06-03 16:56
@Justinzobel you could fix this by different ways. But in my opinion, the best way to do this is uninstalling the antivirus module, run an apt-get update and then, install the last version of antivirus that will be installed without any issue.

I can confirm the issue as fixed, but if you have unmet or broken dependencies, you'll need to act as I said.

Regards!

**Comment by ivosm** [comment] 2020-06-03 18:17
I've just tested installation of antivirus package on zentyal 6.2, where it wasn't installed before and the behavior hasn't changed, i.e. it is still with dependencies like "= 0.102.2" like @Justinzobel reported . 
I have only restricted knowledge of deb packaging, but looking at http://packages.zentyal.org/zentyal/, it looks like only the version 6.1.3 was fixed but not the 6.2.0 .

**Comment by Justinzobel** [comment] 2020-06-03 23:29
> @Justinzobel you could fix this by different ways. But in my opinion, the best way to do this is uninstalling the antivirus module, run an apt-get update and then, install the last version of antivirus that will be installed without any issue.
> 
> I can confirm the issue as fixed, but if you have unmet or broken dependencies, you'll need to act as I said.
> 
> Regards!

The antivirus modules isn't installed, it was removed during upgrade to 6.2. The screenshot above was from the Zentyal components section where I was trying to install them.
![image](https://user-images.githubusercontent.com/1370117/83698841-9e787180-a641-11ea-80af-8acdc70b05a2.png)

**Comment by GlenJ-GH** [comment] 2020-06-04 00:07
At this moment the only way I have been able to get the zentyal antivirus and mailfilter packages installed is to download the zentyal-antivirus_6.2.0_all.deb package and edit the 'control' file in there which dictates what versions of clamav are valid then re-package it into a .deb file and install it manually with dpkg.  After that I was able to install the mailfilter through the zentyal dashboard.

NB: 'freshclam' has to run before antivirus shows as running on the desktop.  Too cold here in Melbourne to be patient so I ran it manually to get it going and all seems to be running fine so far.

**Comment by Justinzobel** [comment] 2020-06-04 00:08
@GlenJ-GH I'm in Adelaide and it's freezing here too. But I am willing to wait until an official fix comes in so I can ensure it's all working correctly for future updates, etc.

**Comment by GlenJ-GH** [comment] 2020-06-04 00:10
I am waiting here too.  I have done all this on a VirtualBox setup to take it for a test-drive before I go live with it.

**Comment by brunolorente** [comment] 2020-06-04 08:20
Sorry guys, we released the code but we didn't put the new package into the packages repo. The new package is already uploaded and available for all of you.

Remember to make an apt-get install -f if is needed.

Many thanks for your time!

**Comment by Justinzobel** [comment] 2020-06-04 08:55
Thanks for the fix Bruno, installed smoothly.

**Comment by ivosm** [comment] 2020-06-04 09:13
Yes, now it works. Thanks.
