### ISSUE TITLE
After Zentyal version ~3.5 PPPoE connection is not obtain the gateway

### ISSUE THREAD

**Issue by nntc** [zentyal/zentyal#1880] opened 2019-06-11 19:12 UTC
Developers! Help!

After Zentyal version ~3.5 PPPoE connection is not obtain the gateway (In version 6.0 - **ALSO NOT WORKING**).

When I add gateway by hand (ip route add default via `here address behind p-t-p PPPoe Addr`) then Zentyal server can access to internet, but workstations in zentyal local network (which ise zentyal as gateway) does not have access to internet.

If i try add default gw by hand from zentyal web interface then form is not success validation.

Problem exists about 5-7 years :-( (https://forum.zentyal.org/index.php?topic=8525.0)?

**Comment by tomasz89** [comment] 2019-06-19 11:22
I've just had this problem tonight after getting a new Internet connection. It's a pretty sloppy miss by the team, thankfully the fix is easy.

When transitioning from Perl's TryCatch::Lite to TryCatch, they missed the ppp module. A simple grep should have found this!

Anyway, in /usr/share/zentyal-network/ppp-set-iface.pl, line 24 (at least in my version):
use TryCatch::Lite;
Change this to:
use TryCatch;

I found this by examining the /etc/ppp/ip-up.d/zentyal-ppp-up script. I edited this to enable debug/logging output, fed the parameters in to the program that's run whenever a new PPPoE link is established, which runs:
/usr/share/zentyal-network/ppp-set-iface.pl <ethernet interface> <ppp interface> <external IP address>

When I ran this, I got module import errors on TryCatch::Lite. I figured that was bad..

**Comment by tomasz89** [comment] 2019-06-19 11:34
Created pull request #1882

**Comment by brunolorente** [comment] 2019-09-05 12:03
At the moment we cannot reproduce this issue, also many customers and Zentyal users are using this feature without errors... anyway, we are going review this feature in order to find issues. Thank you for your time @tomasz89 and @nntc

**Comment by tomasz89** [comment] 2019-09-05 19:40
The exception library in use is wrong.. did you see the code? Bizarre, at the time I did a fresh install and reproduced it immediately.

**Comment by giuseppepaolo** [comment] 2019-09-25 16:10
Same error here with Zentyal 6.0.1. I change the TryCatch::Lite like the @tomaz89, but not solved yet. When I save the configurations, show me the error at modules network and squid.

**Comment by tomasz89** [comment] 2019-11-02 20:48
Patch enclosed in the hopes that it might get the attention needed.

--- ppp-set-iface.pl.bad	2019-06-19 19:11:13.687186483 +0930
+++ ppp-set-iface.pl	2019-11-02 13:51:33.145930564 +1030
@@ -21,7 +21,7 @@
 use EBox;
 use EBox::Global;
 use EBox::Exceptions::Lock;
-use TryCatch::Lite;
+use TryCatch;
 
 EBox::init();

**Comment by brunolorente** [comment] 2019-11-05 07:25
Fixed in c561266c09f6edb1f581142fc9770ad058a047f3

**Closed by brunolorente** 2019-11-05 07:25 UTC
Labels: Status: Fix, Type: Bug

**Comment by Opensoftwarecr** [comment] 2020-09-16 21:12
Hello,
I just installed Zentyal version 6.2 and I have the same error, pppoe does not work. Even modifying the trycatch instruction

**Comment by tomasz89** [comment] 2020-09-16 23:30
Can you please provide the logs so we can see the results of what's going on?

**Comment by AurelienBROSIUS** [comment] 2020-10-01 15:04
I have the same problem on zentyal 6.2

I uncommented defaultroute from the /usr/share/zentyal/stubs/network/dsl-providers.mas file
and create a firewall.postservice file in / etc / zentyal / hooks containing "iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE"

If I go to the web interface and save the network module, the pppoe connection works but an error appears on the network module. If I reboot, the interface does not go up. here is the error in the log file /var/log/zentyal/zentyal.log : 

Exit value: 1 at root command /usr/share/zentyal/unblock-exec /sbin/ifup --force -i /etc/network/interfaces zentyal-ppp-eth1 failed.
Error output: ethtool: bad command line argument(s)
 For more information run ethtool -h
 run-parts: /etc/network/if-up.d/ethtool exited with return code 1

**Comment by Neustradamus** [comment] 2020-11-05 03:02
@brunolorente @djoven89: Can you look comments? There is a problem...
