### ISSUE TITLE
Unable to login: MyDBEngine script error

### ISSUE THREAD

**Issue by alfredonodo** [zentyal/zentyal#2065] opened 2021-07-01 07:30 UTC
Hi,
I'm using zentyal 7.0.4 with modules: network, firewall, antivirus, IDS, logs, ftp, vpn (all upgraded to latest version). Since one week, I have a problem about login into zentyal dashboard. In few words, there is an error on a MyDBEngine.pm script.
Zentyal shows the possibility to report the problem, but if I click on the item and I complete the description, it does not work (redirect to login page).
The problem disappears if I reboot the system, but it comes back after a while. I do not know if it something related to [this](https://github.com/zentyal/zentyal/issues/2055) (I have mysql 8.0.25).
Thank you
![Zentyal error](https://user-images.githubusercontent.com/41476198/124084398-76269680-da3e-11eb-8897-c7d9c38536f5.png)

![Zentyal error2](https://user-images.githubusercontent.com/41476198/124084175-3e1f5380-da3e-11eb-9fb4-be423ee62155.png)
![Zentyal error3](https://user-images.githubusercontent.com/41476198/124084198-44adcb00-da3e-11eb-8f3b-9375f95c7df0.png)

**Comment by djoven89** [comment] 2021-07-07 15:51
Hi @alfredonodo ,

Please note that this is a duplicate of the Issue [2055]. You can follow
the updates in the original Issue. Closing the Issue.

[2055]: https://github.com/zentyal/zentyal/issues/2055

Best regards, Daniel Joven.

**Closed by djoven89** 2021-07-07 15:51 UTC
Labels: Type: Bug
