### ISSUE TITLE
brunolorente contact? email?

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1931] opened 2019-12-18 07:50 UTC
@brunolorente: It is hard to talk with you!

What is your email address?

Comments are always not seen by you?

About the last changes, it is not complete!

Look my comment on https://github.com/zentyal/zentyal/issues/1916...

**Comment by brunolorente** [comment] 2019-12-18 11:00
Hi @Neustradamus 

I do read all the bug reports and comments, but do not necessarily have time to respond each and every one of them with detail. Some are closed quickly because they are simply not relevant and we want to keep the tracer as clean as possible. I might be wrong in some cases, but then again, it is easy to re-open if necessary. 

Please note that one of the main purposes of GitHub (for us) is to track and fix bugs. A little while ago we prepared a bug report template that should help to submit bug reports make easier to understand what is the problem & how to reproduce it, which consequently helps to decide if the bug report can be accepted and how it should be prioritized. We would very much appreciate that this template would be used for all issues reported via GitHub.

About #1916 ... we have discussed internally and we thought that the fix offered is the most accurate as possible too be compliant with the rest of the system and the other users

Thanks a lot for your time, but I must close this as invalid!

**Closed by brunolorente** 2019-12-18 11:00 UTC
Labels: Reason: Invalid, Status: Nothing to do, Type: Enhancement
