### ISSUE TITLE
Ubuntu 20.04 is here

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1964] opened 2020-04-25 21:20 UTC
Ubuntu 20.04 is here
- https://ubuntu.com/

**Comment by brunolorente** [comment] 2020-04-27 11:33
Two thinks regarding to this:
1. Please, use the provided issue template to report new issues.
2. This is not a bug, so I'll close the issue...

Sorry @Neustradamus... we value the active users like you, but we have a forum to this kind of stuff...

Regards!

**Closed by brunolorente** 2020-04-27 11:33 UTC
Labels: Reason: Invalid, Status: Nothing to do
