### ISSUE TITLE
antivirus module keeps shutting down on it's own.

### ISSUE THREAD

**Issue by tecfs** [zentyal/zentyal#2099] opened 2022-07-25 12:41 UTC
I keep receiving "unchecked" emails.  When I check the antivirus module on my server is has stopped and needs to be restarted.

This happens very frequently.  Typically needs to be restarted more than once a day.

**Comment by RetMC** [comment] 2022-07-28 15:40
Sometimes Clamav shuts down when reloading new virus definitions. That may happen because of lack of RAM. 
Check how much RAM is free in your system. 
You could change ClamAV settings to use less memory with  "ConcurrentDatabaseReload" flag.
Found it on https://github.com/mailcow/mailcow-dockerized/issues/3761
Hope it helps

**Comment by djoven89** [comment] 2022-08-02 08:30
Hi @tecfs ,

I'm sorry but I have to close this ticket because you did not follow the template. Please, read the comment that @RetMC wrote and if the issue persists and you believe that it is caused by a bug, create a new ticket but this time, using the template and providing there all the information you can, like log files, your server resources, its load, etc. Otherwise, remember that you can use the [forum].

[forum]: https://forum.zentyal.org/

**Closed by djoven89** 2022-08-02 08:30 UTC
Labels: Type: Bug, Reason: Invalid
