### ISSUE TITLE
Reader DN Accepts Concatenation of First name and Last name instead of username !!!

### ISSUE THREAD

**Issue by gitnetworklab** [zentyal/zentyal#2050] opened 2021-04-24 17:08 UTC
**Describe the bug**
I use Portainer to manage my Docker Endpoints. I tried to use LDAP authentication in it with Zentyal. I had to enter reader DN in Portainer to read the Zentyal Database. But, when I configured the DN :
Reader DN Accepts Concatenation of Username and Password instead of username.
Struggled a lot to find the solution as above, somewhere on the internet I found this solution to use Concatenation of First name and Last name in this form CN=Administrator Admin,CN=Users,DC=gitnetworklab,DC=com.
Wherein "Administrator" is First name and "Admin" is Last name.

**To Reproduce**
1. Configure Portainer in test lab and try to use LDAP authentication with Zentyal and enter read DN details,
2. With username it will not work.
3. If you try with Concatenation of First name and Last name, it will work.

**Expected behavior**
It should work with username only as it happens in Microsoft Windows server.

**Zentyal OS (please complete the following information):**
 - Version: 7.0
- LDAP

**Comment by djoven89** [comment] 2021-04-27 15:01
Hi @gitnetworklab,

I'm sorry but your issue isn't caused by a bug, you just need to find out the proper configuration parameters, I recommend you to create a post in the forum.

Before closing the ticket, please, check the following points:

1. Samba doesn't have a domain user with read only permission, so, you will need to use an admin user.

2. To get the DN of one domain users, use the following command:

	```
	## To get all LDAP objects
	ldbsearch -H /var/lib/samba/private/sam.ldb
	
	## To get all the information from a domain user called 'dockeradmin'
	ldbsearch -H /var/lib/samba/private/sam.ldb 'sAMAccountName=dockeradmin'
	```

3. Make sure that the firewall module has a rule that allows the LDAP authentication.

Hope it helps.

Best regards, Daniel Joven.

**Closed by djoven89** 2021-04-27 15:01 UTC
Labels: Type: Bug, Type: Configuration Mistake
