### ISSUE TITLE
No dhcp client after Zentyal reboot 6.1

### ISSUE THREAD

**Issue by vnavna01** [zentyal/zentyal#1962] opened 2020-04-24 12:43 UTC
**Describe the bug**
After restarting or snapshot restore the Zentyal VM the eth0 network goes offline and I need to run sudo dhclient eth0 to start the network interface again.
This happens in the Developers and Commercial versions of Zentyal.

**To Reproduce**
1. Restore a VM snapshot or reboot Zentyal VM
2. After a reboot run ip a or ifconfig to see the output
3. See error No IP address assigned
4. Run sudo dclient sth0
5. Run ifconfig again to verify that an IP address is assigned to eth0

**Expected behavior**
The network interface should start up after a reboot.

**Screenshots**

**Zentyal OS (please complete the following information):**
 - Version:  6.1
  - No Modules installed yet

**Other OS (please complete the following information):**
 - OS:Running on ESXi 6.7 U2

**Additional context**

**Comment by brunolorente** [comment] 2020-05-28 14:08
Hi @vnavna01 

We couldn't reproduce this issue, also, we never get any report about this... We are always working over VMs as you could imagine and we never get any issue like this.

Anyway, you could check the '**/var/log/zentyal/zentyal.log**' and '**/var/log/syslog**' when you get the issue.

Do you have some weird setup for the network module?

Regards!

**Comment by brunolorente** [comment] 2020-07-15 17:38
@vnavna01 I'm going to close the issue in order to continue in #1976

**Closed by brunolorente** 2020-07-15 17:38 UTC
Labels: Reason: Cannot reproduce, Status: Question, Type: Bug
