### ISSUE TITLE
Multiple DNS (NAMED) problems after 7.0 upgrade

### ISSUE THREAD

**Issue by seederp2p** [zentyal/zentyal#2038] opened 2021-03-10 10:11 UTC
**Describe the bug**
Hi!

So I upgraded to 7.0.

Everything looked ok till I found that DNS is not replicating and that my machines can't update their records.
Also found that some external records just won't resolve it's ip's.

If I add a record manually at one DC the record won't replicate to other DC's.

I've 4 DC's (all zentyal 7.0)

Some logs:

Mar 10 03:16:33 XXXdc01 named[1270]: samba_dlz: ldb: replmd_add: unable to find invocationId
Mar 10 03:16:33 XXXdc01 named[1270]: samba_dlz:
Mar 10 03:16:33 XXXdc01 named[1270]: samba_dlz: failed to modify DC=XXXDSK04,DC=XXX.local,CN=MicrosoftDNS,DC=DomainDnsZones,DC=XXX,DC=local - WERR_GEN_FAILURE
Mar 10 03:16:33 XXXdc01 named[1270]: samba_dlz: cancelling transaction on zone XXX.local

I also have some logs like this:

DNS format error from 208.67.222.222#53 resolving brightcloud.com/DS: invalid response

Please help.

EDIT: Also Domain objects are not replicating. If I do a samba-tool drs replicate with  --full-sync it it's synced.

**Comment by djoven89** [comment] 2021-03-12 17:34
Hi @seederp2p,

Just to inform you that the issue was caused by a bug in Samba, which is explained [here]. We have added [this workaround] in the code but just for new additional domain controller provisions, so, for existing upgrades which have configured the Domain Controller as Additional, you will need to run the following command:

```
sudo samba_upgradedns --dns-backend=BIND9_DLZ
```

After that, you just need to restart the DNS module as follows:

```
sudo zs dns restart
```

Anyway, we are documenting the complete produce in the official Zentyal 7.0 documentation, which will be released next week.

[here]: https://bugzilla.samba.org/show_bug.cgi?id=14535
[this workaround]: https://github.com/zentyal/zentyal/commit/d67ccc1325365ae2fd7b1a28e8788b4b766cb4e9

Best regards, Daniel Joven.

**Comment by seederp2p** [comment] 2021-03-12 17:38
Ok.

Latter next week I might try to upgrade all my 4 zentyal DC's.

So I understand that if I upgrade now it's going to upgrade to 7.0.2, where this issue is fixed, right?

**Comment by seederp2p** [comment] 2021-03-13 15:48
Ok.

The replication part is ok.

However I still have problems resolving some DNS names.
I Use OpenDNS as DNS Forwarders:

Mar 13 15:43:55 XXXdc01 named[1401]: DNS format error from 208.67.222.222#53 resolving zohocorp.com/DS: invalid response
Mar 13 15:43:55 XXXdc01 named[1401]: DNS format error from 208.67.220.220#53 resolving zohocorp.com/DS: invalid response
Mar 13 15:44:28 XXXdc01 named[1401]: DNS format error from 208.67.220.220#53 resolving zohosalesiq.com/DS: invalid response
Mar 13 15:44:28 XXXdc01 named[1401]: DNS format error from 208.67.220.220#53 resolving zohostatic.com/DS: invalid response
Mar 13 15:44:49 XXXdc01 named[1401]: DNS format error from 208.67.220.220#53 resolving msedge.net/DS: invalid response

**Comment by djoven89** [comment] 2021-03-16 13:55
Hi @seederp2p ,

I tried to reproduce this bug but I couldn't. I configured two Zentyal 6.2 servers, one was configured as Domain Controller StandAlone and the other as Additional Domain Controller. After confirm that the environment was working correctly, I upgraded the Additional Domain Controller to 7.0 without issues.

I'm wondering, are you using Dynamic DNS in the Additional Domain Controller?

**Comment by seederp2p** [comment] 2021-03-16 14:00
Hi!

Nop. No dynamic DNS configured.

Right know I've my Zentyal's 6.2.8 working perfectly (I rolled back again).
No error messages, everything working just fine on 6.2.8.

**Comment by seederp2p** [comment] 2021-03-16 14:02
By the way... all my DC's are "additional domain contollers".

**Comment by djoven89** [comment] 2021-03-16 15:05
Hi @seederp2p ,

The server that owns the FSMO roles, which operating system and version has?

**Comment by seederp2p** [comment] 2021-03-16 15:11
Hi!

All DC servers are Zentyal servers.

**Comment by djoven89** [comment] 2021-03-29 11:01
Traced the issue with @seederp2p to DNS errors in the existing 6.2 deployment. Once these were solved, the upgrade was successfully completed.

**Closed by djoven89** 2021-03-29 11:01 UTC
Labels: Status: Needs review, Type: Bug
