### ISSUE TITLE
Zentyal 7.0 Temporary failure in name resolution

### ISSUE THREAD

**Issue by Everglase** [zentyal/zentyal#2026] opened 2021-01-30 04:36 UTC
**Describe the bug**

After installing Zentyal 7.0 from scratch there isn't a problem and DNS resolution on the Zentyal install works fine in resolving external domain names. But after the initial web based configuration the system loses the ability to resolve external domain names. Which also means that apt fails to work.

By entering a nameserver entry into the resolv.conf file to another DNS service we can restore the DNS resolution, but after reboot the issue returns.

I have tried on multiple installations on both virtual and physical hardware and the issue always presents itself after the network configuration section of the initial web based configuration. I have resorted back to 6.2 for new installations and using the exact same entries in the network configuration during the installation and the initial configuration is not presenting the issue that is present in 7.0

**Zentyal OS (please complete the following information):**
Version: 7.0
DNS, DC, DHCP

**Comment by Amado8509** [comment] 2021-01-31 04:33
(Transalate to english )
in my case I get error right almost at the end of the first part of the installation before restarting, just when you should update the grub there, it fails and does not install the grub, it happens to me in virtual environment but I have tested with several versions Zentyal 6.2 and others  and I have only tested with this 7.0, I have changed Up then, version 7.0 arrives in Virtual Box 6.1.18

(Spanish)
(en mi caso me da error justo casi al terminar la primera parte de la instalación antes de reiniciar , justo cuando debe de actualizar el GRUB ahí da error y no instala el GRUB , me pasa en entorno virtual pero he probado con varias versiones Zentyal 6.2 y anteriores y solo me pasa eso con esta 7.0 , he cambiado casi todos los parámetros de la Pc virtual y hace lo mismo al tratar de actualizar el GRUB para posteriormente reiniciar ! hasta ahí llega la versión 7.0 en Virtual Box 6.1.18)

**Comment by DigiAngel** [comment] 2021-02-05 20:35
I concur...running into this issue as well.  I see the forwarders in /etc/bind/named.conf.options, but traffic captures show no requests to any of the forwarders, and just to the root servers.  Manually hard coding a dns server in /etc/resolv.conf is a temp workaround for apt, but yes...something is not working.  Fresh install here as well.

**Comment by marco4github** [comment] 2021-02-07 19:41
> **Describe the bug**
> **Zentyal OS (please complete the following information):**
> Version: 7.0
> DNS, DC, DHCP

I can confirm this and want to add some detail:

This is only an issue when your Zentyal 7 is behind a Firewall and you want to use a DNS forwarder.
First, it tries to resolve the name using the root NS - which of course fails.
At the end it tries to resolve via the DNS forwarder but though there is a response, it fails.

Hopefully someone will take care of this painful bug soon.

**Comment by DigiAngel** [comment] 2021-02-12 17:10
Any movement on this?  I'm dead in the water to even test this until it's fixed.  I didn't have this issue with 6.2.

**Comment by egantz09** [comment] 2021-02-15 15:14
Any fix released??

**Comment by DigiAngel** [comment] 2021-03-08 18:52
Anything?  This has been since January...

**Comment by Everglase** [comment] 2021-03-09 08:31
Not from what I have seen or my testing. 

I don't know how to escalate this issue.

**Comment by DigiAngel** [comment] 2021-03-09 16:12
Heh...if the community version is a way to entice folks to purchase, this isn't the way to do it ;)  I'm over this..trashed the VM and will find something different to use.

**Comment by brunolorente** [comment] 2021-03-12 16:05
@DigiAngel @marco4github @Everglase You proved a beta version... I think that all your issues have been fixed yet.

Today, 2021/03/12 we couldn't reproduce any of this issues, it would be great if you attach some log trace!

**Comment by brunolorente** [comment] 2021-03-12 16:06
I forgot it, a little advice, please, open a new issue for every different issue, always using the provided issue template

**Comment by nickpiggott** [comment] 2021-03-15 09:26
I also saw this behaviour with a fresh install of Zentyal 7.0. Not behind any firewalls, so access to root servers was possible. I saw lots of messages from named in the syslog complaining it had bad cache hits and couldn't trust results.

I was able to variably clear the problem by deleting the contents of /var/cache/bind *after* bind had been started, and then restarting it.

However, I also wonder if it's connected to the DLZ plugin for Samba AD integration. I didn't setup enough debug, but that will be my next step if it happens again. (The DLZ plugin is at 11, bind is at 16, so there's a version mismatch).

**Comment by arakan94** [comment] 2021-03-18 19:51
I have same problem - clean 7.0 installation, ADC, DNS, DHCP. I have included details and everything I've tried to solve the issues. It is reproducible.

[zentyal dns bug.txt](https://github.com/zentyal/zentyal/files/6166837/zentyal.dns.bug.txt)

**Comment by arakan94** [comment] 2021-03-19 12:01
@brunolorente  Deleting the contents of /var/cache/bind after bind had been started, and then restarting dns seems to make it work until I restart the server after which it is broken again.

Is the text file I attached sufficient for you to reproduce the issue?

**Comment by djoven89** [comment] 2021-03-30 15:49
Hi,

After several tests, I could reproduce the issue. Apparently, it's an issue with DNSSEC, concretely, when the DNS module is installed without Internet access.

You can get more information by running the following command:

```
sudo journalctl -u named
```

In my case, the relevant records were:

```
mar 28 13:05:18 zentyal named[3530]: dns_rdata_fromtext: managed-keys.bind:10: near eol: unexpected end of input
mar 28 13:05:18 zentyal named[3530]: managed-keys-zone: loading from master file managed-keys.bind failed: unexpected end of input
mar 28 13:05:22 zentyal named[3530]: managed-keys-zone: Unable to fetch DNSKEY set '.': failure
Mar 28 13:08:47 zentyal named[3195]: managed-keys-zone: DNSKEY set for zone '.' could not be verified with current keys
```

I could fix the issue with the following workaround:

1. I checked that my network module was correctly configured.

2. I deleted the following cache files: 

```
sudo rm -v /var/cache/bind/managed-keys.bind*
```

3. I restarted the DNS module:

```
sudo zs dns restart
```

4. I could see that the DNSKEY was correctly updated:

```
egrep 'DNSKEY.*trusted' /var/log/syslog

Mar 28 13:15:21 zentyal named[3195]: managed-keys-zone: Initializing automatic trust anchor management for zone '.'; DNSKEY ID 20326 is now trusted, waiving the normal 30-day waiting period.
```

5. The domain resolution worked again:

```
ping google.es
```

**Comment by nickpiggott** [comment] 2021-03-30 17:20
I can confirm the same log entries and file behavour that @djoven89 has explained above.

Has something changed with the default bind behaviour? I would have assumed that a missing DNSSEC key would have not caused a fatal error in resolution, just warnings in the log? I've not noticed this problem before, having used Zentyal (and bind) for quite a while.

**Comment by arakan94** [comment] 2021-04-01 10:19
`sudo rm -v /var/cache/bind/managed-keys.bind*` followed by restart fixed the issue for me. Thanks!

**Comment by lucrus73** [comment] 2021-04-05 19:29
Only to let others now, I'm facing the same issue with a upgraded from 6.2.9 Zentyal 7.0 instance. The workaround here above worked for me too.

**Comment by nickpiggott** [comment] 2021-04-06 07:52
Next time this happens, can someone grab a copy of the files in /bar/cache/bind before deleting them.

I'm wondering if they're getting corrupted as they're being downloaded and the default behaviour for bind is to fail if they're present but corrupted.

**Comment by lucrus73** [comment] 2021-04-06 08:03
@nickpiggott You'd better stick your request at the top of this issue if possible or add it by editing your first post in this issue, otherwise people read from the top, try the suggested solutions and reach your request when it's too late.

**Comment by brunolorente** [comment] 2021-04-07 16:12
Thank you for your help in locating the issue and confirm that the workaround works. At the moment it would seem that the reported behavior happens only when you are installing the DNS module without Internet access. 

After looking into this for quite some time, we have concluded that this is due to a Bind9 limitation. In previous Ubuntu Server versions this didn't cause fatal error, but in 20.04 stricter checks apply. 

We have evaluated integrating the workaround, but eventually disregarded this option because there might be N scenarios where it should be executed and too many evaluations should be done in the code (or execute it always, which would be a mess). 

We will document the behavior and the workaround and close the issue for now. If there is further information that can help to provide a permanent solution, feel free to post it here, if necessary, the issue can be re-opened later.

**Comment by nickpiggott** [comment] 2021-04-08 09:36
Adding this for future debugging.

I had this problem happen yesterday during normal operation when my Internet connection dropped out for a short period. After the dropout, bind was failing to resolve domain names, so I had to clear the cache and restart it.

So it can happen at any time if the Internet connection goes down, not just at startup.

**Comment by digitalampi77** [comment] 2021-04-14 11:51
Update from dev.6.2 version to dev.7. DNS name resolution not worked and squid proxy stopped.
After this I was clean install 7.0 and same errors. Then I'm configure DNS forwarders. Yesterday I was insert new network object and DNS not resolving proxy stopped. Sorry for my bad english.

**Comment by Neustradamus** [comment] 2021-04-14 14:55
The fix has been added?

**Comment by nickpiggott** [comment] 2021-04-17 06:55
This problem is still occurring for me, at unpredictable intervals. It may be linked to temporary short outages of my Internet connectivity, but once a failure has occurred, it apparently won't correct itself unless bind is stopped, the cache cleared, and bind restarted.

I understand this is a behaviour change in bind, but is there any guidance / possibility to configure bind to follow the previous (less strict?) behaviour?

**Comment by nickpiggott** [comment] 2021-04-20 07:56
**An update:**

The problem seems to be linked to change in BIND's default behaviour for dnssec-validation.

I have a network interface which renews its DHCP address fairly frequently (it's a 4G modem). At each renewal, named is stopped and restarted, to bind to the new address. When named starts, it tries ONE time to get the RRSIG for the root domain, and if that fails, it will not respond to DNS requests for anything other than the domain(s) it is authoritative for (usually your own domain).

In my scenario I also have an interface which is connected to my ISP, so should be able to handle the request for the RRSIG, but because of the way Zentyal rebuilds the firewall (iptables) as a result of any DHCP IP address change, frequently I lose connectivity for 10 seconds or so throughout the entire system, even if just the DHCP address on my (backup) 4G modem has changed. I suspect it's at this moment that BIND tries to acquire the RRSIG.

I have made a temporary change to /etc/zentyal/stubs/dns/named.conf.options.mas  to include the line
dnssec-validation yes;
which forces BIND to use the keys it is pre-configured with, rather than trying to update them. I'm trying this out to see if it helps.

**Comment by brunolorente** [comment] 2021-05-03 11:02
Hi @nickpiggott,

We are already researching about this issue (about what could be the better fix).

I guess we'll find a definitive fix along this month.

Many many thanks for your time!

**Comment by nickpiggott** [comment] 2021-05-03 13:15
Update - since changing the bind configuration to include

dnssec-validation yes;

I have had no problems. Although I might say (given the problems I'm having with the firewall and a frequently changing DHCP address) that making the firewall changes less dramatic on an WAN IP address change would be great too. 👍

**Closed** 2021-05-18 08:54 UTC
Labels: Status: Roadmap, Type: Enhancement

**Comment by metafarion** [comment] 2022-11-10 03:55
I ran into this exact situation earlier today; DNS forwarding doesn't work after Zentyal 7.0 is installed without an active internet connection.  djoven89's solution above fixed the problem immediately, but it should not have arisen in the first place, especially over a year after the issue was marked Fixed.

**Comment by Everglase** [comment] 2023-03-27 10:55
Now over 2 years since I posted this issue and @djoven89 posted the work around ant the problem is still persistent. 

I do a number of deployments where there is limited internet access or only internet at certain times and I'm having to use a  watchdog to check for internet access then run a script to clear the cache and restart bind.

Surely after 2 years there has to be a solution.

**Comment by Rubarius** [comment] 2023-03-28 03:28
Zentyal 7.0.5 error is relevant, enabled service restart in cron.
